spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/growable?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: cv93523827!!
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 92834c027009e695e46bf5163f5a8643
            redirect-uri: http://ec2-13-209-18-185.ap-northeast-2.compute.amazonaws.com:8080/api/auth
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
                - profile_nickname
                - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakaoNickname

kakao:
  clientId: 92834c027009e695e46bf5163f5a8643
  secret: PtzmYmdLi1BIGXgGa1ElNl7YXYcQKVRY